config/routes.rb
Rails.application.routes.draw do
	root to: 'static_pages#home'
	
	resources :projects
	resources :contacts

	get '/projects', to: 'projects#index'
	get '/contacts', to: 'contacts#index'	
	get '/education', to: 'static_pages#education'	
	get '/', to: 'static_pages#home'
  	
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord
	#attr_accessor :name, :email, :message

	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

	# Validations
	validates :name, presence: true, length: { maximum: 50 }
	validates :email, presence: true, format: { with: VALID_EMAIL_REGEX }
	validates :message, presence: true, length: { maximum: 500 }
end

app/models/project.rb
class Project < ApplicationRecord
	#attr_accessor :name

	validates :name, presence: true, 
			         uniqueness: { case_sensitive: false }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
	def index		
	end
	def show
	end
	def new
		@contact = Contact.new(params[:contact])
	end	
	def create
		@contact = Contact.new(contact_params)
		if @contact.save 	# successful save
			# send contact form to email
			ContactMailer.with(contact: @contact).new_contact_email.deliver_later
			
			flash.now[:success] = "The contact request has been processed correctly. Thank you for your time!"
			render 'index'
		else
			render 'new'
		end
	end

	private

	def contact_params
	  params.require(:contact).permit(:name, :email, :message)
	end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

	def index
		@projects = Project.all
	end
	def show		
	end	
	def new
	end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
  def education
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/contacts/index.html.erb
<% provide(:title, 'Contact') %>
<!DOCTYPE html>
<html>
  <body>
    <h1><strong>Contact</strong></h1>
    <p class="text-presentation">If for any reason you want to contact me, for example to ask for more information, make suggestions, discuss projects, information on education, etc., you can do so by clicking on the chat image.  This will take you to a form that you can fill in and send it to me. I will try to answer you as soon as possible. </p>
    <h3 align="center"><%= link_to image_tag("contact_me.jpg", size:"150x150"), new_contact_path %></h3>
  </body>
</html>

app/views/contacts/new.html.erb
<% provide(:title, 'Contact') %>
<!DOCTYPE html>
<html>
  <body>
    <h1>Contact me <%= image_tag("email_icon.png", size:"80x60", hspace:"15")%></h1>
    <div class="row">
		<div class="span6 offset3">
			<%= form_for @contact do |f| %>+
				<%= render 'shared/error_messages' %>
				<%= f.label :name %>
				<%= f.text_field :name %>
				<%= f.label :email %>
				<%= f.text_field :email %>
				<%= f.label :message%>
				<%= f.text_area :message, rows:10, cols:10%>				
				<%= f.submit "Send", class: "contact_button"%>
			<% end %>
		</div>
	</div>
  </body>
</html>

app/views/layouts/_footer.html.erb
<footer class="footer">
	<small>
		AnoobDataScientist by Fernando García
	</small>
	<nav>
	<ul>
		<li><%= link_to "Projects", projects_path %></li>
		<li><%= link_to "Education", education_path %></li>
		<li><%= link_to "Contact", contacts_path %></li>				
	</ul>
	</nav>	
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top">
  <div class="navbar-inner"> 
    <div class="topnav">     
      <nav class="active">        
          <%= link_to "Home", root_path %>
          <%= link_to "Projects", projects_path %>
          <%= link_to "Contact", contacts_path %>
          <%= link_to "Education", education_path %>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/_project_1.html.erb
<h1>PyWinEA, simple complex algorithms</h1>
<h2>Introduction to Evolutionary Computing</h2>

<p class="text-presentation">
The field of Evolutionary Computing is an area of great interest within Computer Science due to its ability to obtain good approximations to complex problems. When I talk about complex problems I am referring to the famous <b>NP-Problems</b>. 
</p>
<p class="text-presentation">
For example, let's imagine that we are dealing with a problem with 100 variables, something quite common nowadays given our great capacity to collect data. Now, within those 100 variables we will have a large number of irrelevant and/or redundant features, something that, for example, can significantly affect the performance of our classification/regression models. In this situation we are interested in finding the best combination of those 100 variables, I mean, finding the best subset of variables. 
</p>

<p class="text-presentation">
In this case the number of possible combinations is given by the following formula (I am enclosing a piece of code written in Python to apply this formula and determine the number of possible combinations):
</p>
		<%= image_tag("project_1/complexity_formula.jpg", :alt => "complexity", :size => "400x200", align:"center", hspace:"20", vspace:"10", class:"profile-image") %>
		<%= image_tag("project_1/complexity_python.jpg", :alt => "complexity Python", :size => "600x200", align:"center", hspace:"20", vspace:"10", class:"profile-image") %>  

<br><br>
<p class="text-presentation">
This gives a total of <b>1267650600228229682971679916032</b> possible combinations, which is somewhat intractable.
</p>

<br>
<p class="text-presentation">
As we cannot explore every possible combination we must find alternatives to try and reduce the number of variables. This reduction may be of interest to us for several reasons.
	<ul class="text-presentation">
		<li>
			Firstly, because of what was mentioned above, to try to improve the <b>performance</b> of the models. 
		</li>
		<br>
		<li>
			Additionally, the reduction in the number of variables is leaving us only with those that are really relevant to the problem, this translates into the <b>generation of knowledge</b>. 
		</li>
		<br>
		<li>
			Finally, some models, for example, in the field of Artificial Intelligence, are computationally very expensive. This implies that the more variables we have, the more time and resources they will consume. Therefore, the reduction in the number of variables allows us to <b>increase the efficiency</b> of the algorithms and models.
		</li>
	</ul>
</p>


<p class="text-presentation">
	In this context, we are interested in reducing the number of variables used as much as possible without affecting the results.
</p>

		<%= image_tag("project_1/basic_ga.jpg", :alt => "complexity Python", :size => "600x300", align:"right", hspace:"20", vspace:"10", class:"profile-image") %>

<p class="text-presentation">
	This is where <b>Evolutionary Algorithms</b> come into play, algorithms that are bio-inspired in the Evolutionary Theory. These are techniques based on populations, in their most basic implementation we would start with a population of individuals, where each one represents a possible solution, which is improved over successive generations. This population is subject to events of <b>variation</b> and <b>selection</b> that guide the evolutionary process in a <b>stochastic</b> way, that is, NOT deterministic. This implies that we will always have a random component that helps us to avoid local minimums (if we consider a maximization problem) by increasing the exploratory capacity of the algorithm along the immense space of possible solutions. The scheme of a basic implementation would be as shown on the right.
</p>


<p class="text-presentation">

	(<i>This is a basic model, there are some variants that are much more complex such as the NSGAII or SPEA2, two types of multi-objective genetic algorithms</i>)
</p>

<p class="text-presentation">
	As I don't feel like going on too long explaining theory and I would like to go a bit more into the practical part I leave here a good introductory reference to this topic (<%= link_to 'Introduction to Evolutionary Computing', 'https://link.springer.com/book/10.1007/978-3-662-44874-8', target: "_blank"%>). However, the basic idea of this type of algorithm is, I think, quite clear.

	<br><br>
	Now let's get on with the framework!
</p>
<br><br>
<h2>PyWinEA framework</h2>

<p class="text-presentation">
This framework can be installed directly via pip (<b>pip install pywinEA</b>) or you can directly access the code and example codes via my <%= link_to 'GitHub', 'https://github.com/FernandoGaGu/pywinEA', target: "_blank"%>.
</p>

<p class="text-presentation">
	As mentioned above, individuals represent the possible solutions to a problem. There are several ways to code the solutions, for example by array of integers, permutations, real values, tree structures, array of binaries, etc. In this case the representation common to all the algorithms is variable length array of integers (although I am currently writing an improved version of the framework with support for binary, integer, permutation and real number representation... I will finish it someday in my free time).
</p>


<p class="text-presentation">
	For example, if our problem consists of 10 variables, an individual may consist of an array with the variables in positions 2, 3 and 8; another individual may consist of the variables in positions 2, 1, 8 and 9, etc. <b>Each individual is essentially a combination of variables</b>. However, we need a way to evaluate how good each individual is, that is, each combination of variables. This is where compatibility with <b><%=link_to 'Scikit-Learn', 'https://scikit-learn.org', target: "_blank"%></b>, one of Python's best-known Machine Learning frameworks, comes into play. In this case, any model already implemented in this huge framework (framework funded by <%= link_to 'Microsoft', 'https://www.microsoft.com', target: "_blank"%>, <%= link_to 'Intel', 'https://www.intel.com', target: "_blank" %> or <%= link_to 'NVIDIA', 'https://www.nvidia.com', target: "_blank" %> among others...) can be used to evaluate the quality of each individual.
</p>

<p class="text-presentation">
	This way running an algorithm is as simple as writing the following code:<br><br>
</p>
		<%= image_tag("project_1/basic_ga_code.jpg", :alt => "BasicGA code", :size => "800x550", align:"center", hspace:"20", vspace:"10", class:"profile-image") %>

<p class="text-presentation">
	<br><br>
	As can be seen in the image, we only need to define the <b>population size</b>, the <b>number of generations</b>, the model used to evaluate the quality (<b>fitness function</b>) of each possible solution (in this case a Scikit-Learn Bayesian classifier), how we are going to evaluate this quality (in this case by cross validation with K = 5 (<i>parameter CV</i>)), the percentage of the population we will <b>annihilate</b> (that is, the percentage of the worst individuals we will eliminate from the population in each generation), the percentage of the individuals we will pass directly to the next generation (that is, the percentage of individuals with the best fitness to pass directly to the next generation (<i>defined by the <b>elitism</b> parameter</i>)), and the <b>mutation rate</b> which will introduce the random component to the algorithm (this random component gives the genetic algorithms the denomination of <b>meta-heuristics</b>, additionally we also introduce random components in the selection process, but I will not go into details).
</p>
<p class="text-presentation">
	In the example we are addressing a problem of <b>supervised classification</b>. The genetic algorithm has tried to find the best possible approximation to an optimal solution reducing the number of features. So the evolution of the algorithm would be something like this:
</p>
		<%= image_tag("project_1/evolution_ga_1.jpg", :alt => "BasicGA code", :size => "530x300", align:"left", hspace:"20", vspace:"10", class:"profile-image") %>
		<%= image_tag("project_1/evolution_ga_2.jpg", :alt => "BasicGA code", :size => "530x300", align:"right", hspace:"20", vspace:"10", class:"profile-image") %>

<p class="text-presentation">
But this framework also provides excellent tools for evaluating solutions with elegant graphic representations. In this way, we can, for example, compute a confusion matrix by cross-validation repetitions in a way that is as simple as that:
</p>

		<%= image_tag("project_1/cm.jpg", :alt => "BasicGA code", :size => "500x400", align:"center", hspace:"10", vspace:"10", class:"profile-image") %>
		<%= image_tag("project_1/ga_evaluator.jpg", :alt => "BasicGA code", :size => "600x120", align:"right", hspace:"10", vspace:"80", class:"profile-image") %>

<p class="text-presentation">
Or even obtain representations of the model's ROC curves and many other metrics with only two lines of code...
</p>

		<%= image_tag("project_1/metrics.jpg", :alt => "BasicGA code", :size => "630x300", align:"center", hspace:"1", vspace:"10", class:"profile-image") %>
		<%= image_tag("project_1/roc.jpg", :alt => "BasicGA code", :size => "500x300", align:"right", hspace:"1", vspace:"10", class:"profile-image") %>


<p class="text-presentation">
	The above result corresponds to a basic implementation of a mono-objective genetic algorithm where the population is subjected to the following processes during each generation:
	<br><br>
	<i>After randomly initializing the individuals in the population and evaluate their quality by assigning them a fitness value, the next steps are repeated for the number of generations defined by the user.</i>
	<ol class="text-presentation">
		<li>
			Select a percentage of the best individuals as an <b>elite</b> (optional).
		</li>
		<br>
		<li>
			Eliminate the worst individuals from the population and replace them with elite or random individuals (optional).
		</li>
		<br>
		<li>
			Select the best individuals in the population for <b>recombination</b> and <b>offspring</b> generation.
		</li>
		<br>
		<li>
			Apply <b>mutation</b> to offspring.
		</li>
		<br>
		<li>
			Merge elite individuals  (if elitism has been used as a strategy) with offspring.
		</li>	
		<br>
		<li>
			Evaluate the quality of the offspring.
		</li>							
		<br>							
		<li>
			Select the offspring as the new population and return to <b>step 1</b>.
		</li>
	</ol>
</p>
<br>
<p class="text-presentation">
	So far so good, this is the basic implementation, however, things can get more complicated. In the example above we have tried to maximise a single objective, that is, we have used only one metric to evaluate the quality of the solutions. However, in many real-world situations we have not one but several objectives, and these are often conflicting objectives. This is where multi-objective genetic algorithms come into play. As the details of these algorithms are somewhat more complicated, I leave here the two references followed for the implementation of the NSGAII (<%= link_to 'reference', 'https://ieeexplore.ieee.org/document/996017', target: "_blank" %>) and SPEA2 (<%= link_to 'reference', 'https://www.researchgate.net/publication/216301720_SPEA2_Improving_the_Strength_Pareto_Evolutionary_Algorithm_for_Multiobjective_Optimization' , target: "_blank"%>).
</p>
<br><br>
		<%= image_tag("project_1/NSGA2.gif", :alt => "BasicGA code", :size => "500x300", align:"right", hspace:"20", vspace:"20", class:"profile-image") %>
<p class="text-presentation">
	However, despite its complexity this framework makes it quite easy to use. For example, let us suppose that we want to maximise a certain metric used to evaluate the quality of a solution and minimise the number of characteristics of an individual (two contradictory objectives). In this case the use of the NSGAII is as simple as shown below.
</p>

<p class="text-presentation">
In this case the Hypervolume Indicator has been used to represent the convergence of the algorithm.  Without any doubt this type of algorithm represents a more effective alternative than the basic model presented above capable of reaching better solutions for the vast majority of real life problems. 
</p>
<p class="text-presentation">
Here again, the visualization tools allow us to explore the results achieved by the algorithm through the aforementioned Hypervolume Indicator, or by showing the non-dominated Pareto'a front of solutions.
</p>
		<%= image_tag("project_1/hypervolume.jpg", :alt => "BasicGA code", :size => "530x300", align:"left", hspace:"20", vspace:"10", class:"profile-image") %>
		<%= image_tag("project_1/pareto.jpg", :alt => "BasicGA code", :size => "530x300", align:"right", hspace:"20", vspace:"10", class:"profile-image") %>


<p class="text-presentation">
By the way, did I mention that it is possible to run any number of algorithms in parallel and compare them? Indeed, the PyWinEA framework allows to run several algorithms in parallel comparing their performance easily. For example, we can compare the non-dominated front of solutions obtained by two algorithms, in this case SPEA2 and NSGAII, for the same problem:
</p>

		<%= image_tag("project_1/pareto_nsga_spea.jpg", :alt => "BasicGA code", :size => "700x500", align:"center", hspace:"20", vspace:"20", class:"profile-image") %>

<br>
<p class="text-presentation">
	And that's it, for more examples and more detailed description of the framework I recommend you to go to my <%= link_to 'GitHub', 'https://github.com/FernandoGaGu/pywinEA', target: "_blank"%>. In the notebooks directory you can find many more examples. 
</p>


<p class="text-presentation">

	Thank you for your time and I hope this mini project has been interesting for you and not too boring.
</p>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AnoobDataScientist | <%= yield(:title) %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/shim' %>
    <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">

      <%= yield %>
      <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>
      <%= render 'layouts/footer' %>
    </div>

  </body>
</html>

app/views/projects/index.html.erb
<% provide(:title, 'Projects') %>
<!DOCTYPE html>
<html>
	<body>
		<h1><strong>Projects</strong></h1>
		<p>
    Below you can find a list of some of the projects I have carried out. If you want more detailed information about the project I encourage you to click on the poster, this will take you to a new page with more comprehensive information about the project.
		</p>		
			<% @projects.each_with_index do |p, idx| %>
				<% if idx % 2 == 0%>
					<% poster_align = "right" %>
					<% title_align = "left" %>														
				<% else %>
					<% poster_align = "left" %>
					<% title_align = "right" %>
				<% end %> 		
				
				<h3 class="project-title", align=<%= title_align %>> <span style="color:black"><%= p.name[0...(p.name.length / 3).to_i] %></span><%= p.name[(p.name.length / 3).to_i..p.name.length] %> </h3>

				<%= link_to image_tag("posters/project_#{idx+1}.jpg", :alt => "project_1", width:"50%", hspace:"30", vspace:"10", align:poster_align), project_path(p) %> 	
				<p class="text-presentation"> <%= p.description %></p>

			<% end %>		
	</body>
</html>

app/views/projects/show.html.erb
<% provide(:title, 'Projects') %>
<!DOCTYPE html>
<html>
	<body>
		<%= render "layouts/project_"+request.original_url.split('/')[-1] %>
	</body>
</html>

app/views/shared/_error_messages.html.erb
<% if @contact.errors.any? %>
	<div id="error_explanation">
		<div class="alert alert-error">
			Impossible to send the contact form. Detected <%= pluralize(@contact.errors.count, "error") %>.
		</div>
		<ul>
			<% @contact.errors.full_messages.each do |msg| %>
				<li>* <%= msg %></li>
			<% end %>
		</ul>
	</div>
<% end %>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>
<!DOCTYPE html>
<html>
  <body>
    <h1>This is a prototype of the <%= yield(:title) %> page.</h1>
    <p>Currently empty</p>
        <div class="row">
		<div class="span6 offset3">
			<%= form_for @contact, url: contact_path do |f| %>
				<%= f.label :name %>
				<%= f.text_field :name %>
				<%= f.label :email %>
				<%= f.text_field :email %>
				<%= f.label :message %>
				<%= f.text_field :message %>				
				<%= f.submit "Contact", class: "btn btn-large btn-primary" %>
			<% end %>
		</div>
	</div>
  </body>
</html>

app/views/static_pages/education.html.erb
<% provide(:title, 'Education') %>
<!DOCTYPE html>
<html>
	<body>
		<h1><strong>Education</strong></h1>
		<br>
			<div class="text-presentation">
		
			<h3 class="university-title", align="left">Complutense University of Madrid (UCM)</h3>
			<br>
			<%= link_to image_tag("ucm_logo.png", :alt => "upm img", width:"30%", align:"left", hspace:"20", vspace:"20"), "https://www.ucm.es/", target: "_blank" %> 
			Considered to be one of the oldest universities in the world and one of the best universities in Spain. This university is home to over 86,000 students and has led to many famous historians, philosophers, poets and Prime Ministers. Its graduates are given ‘lifelong training’ that furnishes them with professional skills allied to their chosen fields of work and alongside their academic studies. 
			<br><br>
			The UCM is in the top 100 in the branch of Arts and Humanities, specifically in position 76, in position 129 in Social Sciences, in position 158 in the branch of Sciences, in position 170 in Life Sciences and Medicine, and in position 229 in Engineering and Technology according to the QS ranking. On the other hand, the The Time’s University Ranking 2020 places the UCM among the 300 best universities in the world in the area of pre-clinical, clinical and health sciences as well as among the 500 best in technology, engineering and computer science. In addition, the UCM is amongst the top 300 universities in the world, in the 201-300 range globally and at the range of 2-5th position in Spain, according to the Academic Ranking of World Universities 2019 (ARWU).
		</div>
		<br><br>
		
		<div class="text-presentation">
		
			<h3 class="university-title", align="right">Polytechnic University of Madrid (UPM)</h3>
			<br>
			<%= link_to image_tag("upm_logo.png", :alt => "upm img", width:"30%", align:"right", hspace:"20", vspace:"10"), "https://www.upm.es/", target: "_blank" %> 
			The Polytechnic University of Madrid was founded in 1971, from the merging of different technical schools, although its origins date as far back as the 18th century. Originally established to teach architecture and engineering in the country, the institution has grown rapidly and is now home to over 41,000 students. It comprises 21 separate schools based on four campuses across Madrid, with its Moncloa Campus denoted as an 'International Campus of Excellence’, a distinction that acknowledges the quality of its research and teaching activity.
			<br><br>
			While the university’s courses have grown and adapted over the years to align with changes in industry, the institution has retained a strong technical focus and boasts several strategic partnerships with professional bodies and external research centres. Its engineering schools are consistently ranked among the best in Europe. With a vibrant multicultural environment, students are encouraged to undertake one of the 400 study abroad programmes it has with higher education institutions in Europe and globally. 
			The Time’s University Ranking 2020 ranking places the university as the 85th best university in the world in industry, innovation and infrastructure.

		</div>
		<br><br>

		<div class="text-presentation">
		
			<h3 class="university-title", align="left">University of the Balearic Islands (UIB)</h3>
			<br>
			<%= link_to image_tag("uib_logo.png", :alt => "upm img", width:"30%", align:"left", hspace:"20", vspace:"40"), "https://www.uib.es/es/", target: "_blank" %> 
			The University of the Balearic Islands is a Balearic Spanish university, founded in 1978 and located in Palma on the island of Majorca. The UIB has gained renowned prestige in research with major international impact. This has been reflected by the results attained by the university in different research quality rankings. The Time’s University Ranking 2020 ranking places the UIB in the 601-800 global position range for the best universities in the world. The ranking also places the UIB as the sixth best in Spain in terms of publication citations of its researchers. The international Highly Cited Researchers 2018 ranking from Clarivate Analytics spotlights five researchers from the University of the Balearic Islands as amongst the most influential in the world, since they have several works amongst the top 1% of the most cited in their field of study for a single year.
			<br><br>
			By discipline, the UIB is in the 401-500 range for the best universities in the world for Education Sciences, Engineering and Technology, and Arts and Humanities. On the other hand, the UIB is amongst the top 500 universities in the world, in the 401-500 range globally and at 11th position in Spain, according to the Academic Ranking of World Universities 2019 (ARWU).

		</div>
	</body>
</html>

app/views/static_pages/home.html.erb
<% provide(:title, 'Home') %>
<!DOCTYPE html>
<html>
	<body>
		<div class="center">		
			<h1><strong>Welcome</strong><br><text style="color:#C2C2C2 ;font-size:30px;">to my personal website</text></h1>	
			
		</div>

		<br>
		<p class="text-presentation">
      <%= image_tag("Profile.jpg", :alt => "profile img", :size => "225x300", align:"left", hspace:"20", vspace:"10", class:"profile-image") %>

    <h2>Current position</h2>

    <h4>PhD student in Computer Engineering at Complutense University of Madrid</h4>
    Life is a path of opportunities and during this journey I was lucky enough to come across a wonderful research group during my internship at the Complutense University of Madrid. This group was dedicated to applying Artificial Intelligence to problems in the clinical field, and look at you, I thought it was an excellent idea. I am currently in the second year of a phD at the Department of Computer Architecture and Automatics of the Complutense University of Madrid where we are developing very cool projects in collaboration with the Hospital Clínico San Carlos.

    In summary, my main role is to research, develop and implement strategies based on the state of the art in the field of Artificial Intelligence to real-world problems in the clinical context.

    <br>
    <h4>Quantitative Analyst at Investing PROFit Wisely, S.L.</h4>
    In many occasions you don't know where life is taking you, in my case, I ended up discovering an exciting world in quantitative analysis in the field of investment, a difficult and therefore exciting area. In this context I am mainly involved in the development and research of Machine Learning algorithms for quantitative analysis based on fundamental and market data for the design of stock market trading and investment strategies.



    <h2>Publications</h2>
    García Gutiérrez et al. (n.d.). Journal of Neurology, Neurosurgery, and Psychiatry. Diagnosis of Alzheimer’s disease and behavioral variant frontotemporal dementia with machine learning-aided neuropsychological assessment using feature engineering and genetic algorithms.
    <br>
    <br>
    García Gutiérrez et al. (n.d.). Elsevier. Design and Implementation of a Tool based on Machine-Learning Techniques for Computer-Aided Diagnosis of Neurodegenerative Diseases.

    <br>
    <h2>Carrer</h2>
    <h4>Internship at the Department of Computer Architecture and Automatics of the Complutense University of Madrid</h4>
    Development of predictive models of neurodegenerative diseases based on Machine Learning techniques and database management.

    <br>
    <h4>Master in Computational Biology at the Polytechnic University of Madrid.</h4>
    Program in Bioinformatics, Big Data and Artificial Intelligence. Master's degree in English with honors in Big Data and Fundamentals of Programming.

    Master's thesis: <b>Tool for Automatic Diagnosis of Neurodegenerative Diseases by Machine Learning Techniques</b>

    <br>
    <h4>Degree in Biochemistry</h4>
    Degree's thesis: <b>Study of the rise and applications of DESI-MS (Desorption Electrospray Ionization Mass Spectrometry) and REIMS (Rapid Evaporative Ionization Mass Spectrometry) technologies.</b>

    <br>
    <h2>Technical knowledge</h2>
    <h4>Programming</h4>
    Proficient in several programming languages, design patterns and several years of programming experience.
    <ul>
      <li>Python</li>
      <li>Cython</li>
      <li>R</li>
      <li>Ruby</li>
      <li>C++</li>
      <li>Java</li>
      <li>Scala</li>
      <li>Julia</li>
      <li>SQL</li>
      <li>Matlab</li>
    </ul>
    Knowledge of frameworks such as: PyTorch, TensorFlow, Scikit-learn, Keras, Spark, openAI gym, Numpy, Pandas, DEAP, Django, Networkx, Matplotlib, Seaborn, Plotly, bnlearn, mlr R, ggplot2, dplyr, tidyr, Caret, Ruby On Rails, ...
    Additionally, I have experience with Weka, SPM12, FreeSurfer and genomic and evolutionary analysis programs/tools.

    <br>
    <h4>Artificial Intelligence</h4>
    Extensive knowledge of supervised/unsupervised classification models, regression, Deep Learning and Reinforcement Learning, heuristic/metaheuristic techniques and probabilistic and causal graphical models.

    <br>
    <h4>Statistical analysis</h4>
    Knowledge of statistical analysis and visualization techniques.

    <br>
    <h4>Databases</h4>
    Relational and non-relational databases as well as Ontology design.

    <br>
    <h4>Others</h4>
    Knowledge of Linux, GitHub, Jupyter, Docker, Pypi and LaTex.

    <h2>Some works</h2>
    <ul>
      <li>Optimization frameworks (<a href="https://github.com/FernandoGaGu/Ant-Colony-Optimisation">antco</a>) (<a href="https://github.com/FernandoGaGu/pywinEA">PyWinEA</a>) (<a href="https://github.com/FernandoGaGu/beagle">beagle</a>)</li>
      <li>Computer vision (<a href="https://github.com/FernandoGaGu/chest-xray-pyspark">chest-xray-pyspark</a>)</li>
      <li>Complex systems modeling (<a href="https://github.com/FernandoGaGu/simamics">simamics</a>)</li>
      <li>Ontology design (<a href="https://github.com/FernandoGaGu/DrugInterBankOntology">DrugInterBankOntology</a>)</li>
    </ul>

		</p>
	</body>
</html>